<?php


namespace Tests\Unit\Http\Controller;


use App\Http\Controllers\PaymentsController;
use App\Http\Service\PaymentsService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Tests\TestCase;

class PaymentsControllerTest extends TestCase
{
    private const PAYER_ID = 1;
    private const PAYEE_ID = 2;
    private const VALUE = 10;

    private $paymentsServiceMock;

    private $controller;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->paymentsServiceMock = \Mockery::mock(PaymentsService::class);
        $this->controller = new PaymentsController($this->paymentsServiceMock);
    }

    public function testHappyPath()
    {
        $request = $this->createARequest(self::PAYER_ID, self::PAYEE_ID, self::VALUE);

        $responseExpected = $this->createJSONResponse(
            PaymentsController::AUTHORIZED_MESSAGE
        );

        $this->paymentsServiceMock->expects('performTransaction')
            ->with(self::PAYER_ID, self::PAYEE_ID, self::VALUE)
            ->andReturn(true);

        $response = $this->controller->transaction($request);

        $this->assertEquals($responseExpected, $response);
    }

    public function createARequest($payerId, $payeeId, $value)
    {
        $request = new Request();

        $request->setMethod('POST');
        $request->request->add([
            PaymentsController::VALUE_KEY => $value,
            PaymentsController::PAYER_KEY => $payerId,
            PaymentsController::PAYEE_KEY => $payeeId
        ]);

        return $request;
    }

    public function createJSONResponse($message, $code = 200)
    {
        return new JsonResponse([PaymentsController::MESSAGE_KEY => $message], $code);
    }
}
